apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sinatra
  template:
    metadata:
      labels:
        app: sinatra
    spec:
      containers:
        - name: sinatra
          image: domanskij/sinatra-api:latest
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 4567
            name: http
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /hello
              port: 4567
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          env:
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: sinatra-secret
                key: postgres_username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sinatra-secret
                key: postgres_password 
          - name: DATABASE_URL
            valueFrom:
              configMapKeyRef:
                name: sinatra-configmap
                key: database_url
          - name: RACK_ENV
            valueFrom:
              configMapKeyRef:
                name: sinatra-configmap
                key: rack_env
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-volume
      volumes:
        - name: postgres-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
