apiVersion: v1
kind: Service
metadata:
 name: sinatra-service
spec:
 selector:
   app: sinatra
 type: LoadBalancer
 ports:
   - protocol: TCP
     port: 4567
     targetPort: 4567
     nodePort: 30000
