apiVersion: batch/v1
kind: Job
metadata:
  name: rails-db-migrate
spec:
  template:
    spec:
      containers:
      - name: sinatra
        command:
        - rails
        - db:migrate
        image: domanskij/sinatra-api:latest
      restartPolicy: OnFailure
