apiVersion: batch/v1
kind: Job
metadata:
  name: rake-db-migrate
spec:
  template:
    spec:
      containers:
      - name: sinatra
        command:
        - rake
        - db:migrate
        image: domanskij/sinatra-api:latest
      restartPolicy: OnFailure
