apiVersion: v1
kind: Service
metadata:
 name: rails-api-service
spec:
 selector:
   app: rails-api
 type: LoadBalancer
 ports:
   - protocol: TCP
     port: 3000
     targetPort: 3000
     nodePort: 30000
